# Reusable Worflow managing Init of Dynamic Template
name: Init Dynamic Template Fork
on:
  workflow_call:

jobs:
  init_fork:
    name: Init Dynamic Template Fork
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
    
      - name: Copy j2 file as normal file
        run: |
          mkdir -p .fork
          touch .fork/link.json
          find . -type f -name "*.j2" -print0 | while read -d $'\0' file;
          do
            newfile=${file%.j2}
            echo "Rename file ${file} to ${newfile}"
            cp "${file}" "${newfile}"
            cat .fork/link.json | jq '. + [{"type": "file", "remote": "${file}", "local": "${newfile}"}]'' > .fork/link.json
          done

      - name: Copy Specific Directories
        shell: bash
        run: |
          find . -type d -name "\$*" -print0 | while read -d $'\0' dirpath;
          do
            lastdir=${dirpath##*/}
            path=${dirpath%/*}
            newdirpath="$path/${lastdir#$}"
            echo "Rename directory ${dirpath} to ${newdirpath}"
            cp -R "${dirpath}" "${newdirpath}"
            cat .fork/link.json | jq '. + [{"type": "dir", "remote": "${dirpath}", "local": "${newdirpath}"}]'' > .fork/link.json
          done

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Init Fork"